# Generated by Django 4.2.27 on 2026-01-13 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveIntegerField(unique=True)),
                ('degree_name', models.CharField(max_length=255)),
                ('enroll_date', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expected_graduation', models.DateField(blank=True, null=True)),
                ('class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classlevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_students',
                'ordering': ['enroll_date'],
            },
        ),
    ]
