# Generated by Django 6.0 on 2026-01-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expected_graduation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
